### ISSUE TITLE
PointerControls on mobile without rotation

### ISSUE THREAD

**Issue by alexey7783** [sparkjsdev/spark#46]
I am using PointerControls and on mobile it is a bit annoying that pinch zoom also rotates the view like a spiral (so moving forward plus rolling like a plane). Which is not neccessary in my opinion. Maybe have a flag or remove it completely? 

Expected: Pinch zoom only moves me forward in the camera direction and no additional rotation. 
Maybe rotation only, when I use two fingers and do a rotation movement alone, with only little movement towards each other (so we would need to distingusih what the user intends to do, rotate the view or zoom)

**Comment by dmarcos** [comment]
CC @asundqui

**Comment by asundqui** [comment]
@alexey7783  we just merged a change that allows you to disable multi-touch roll. Here's an example of how you'd do it:
```
    const controls = new SparkControls({ canvas: renderer.domElement });
    controls.pointerControls.pointerRollScale = 0;
```
Can you verify that this fixes it for you?

**Comment by akutterxressential** [comment]
@asundqui 

Sorry, family weekend prevented an earlier check :-D

(I think?)  I downloaded the commit and used it to test the function

![Image](https://github.com/user-attachments/assets/2ecba9a2-c00b-4af7-8525-4d41963da003)

This is how I use it:

      // Pointer-Steuerung
      const pointerControls = new PointerControls({ canvas: renderer.domElement,
        rotateSpeed: 0.003, slideSpeed: 0.009, scrollSpeed: 0.005, 
        reverseRotate: false, reverseSlide: false, reverseSwipe: false, reverseScroll: false,
        moveInertia: 0.15, rotateInertia: 0.15
      });
	  pointerControls.pointerControls.pointerRollScale = 0;

And this is the error I receive:

![Image](https://github.com/user-attachments/assets/cef436c9-4f6a-4156-9cae-6471ad3d54f6)


What am I doing wrong? Or is the case that I would have to build the repo and I can`t use the dist folder directly? I haven`t setup the build environment for this project

**Comment by asundqui** [comment]
@akutterxressential very easy fix - just a typo :). In my example I set `sparkControls.pointerControls.pointerRollScale = 0`. SparkControls is really just a wrapper that contains a `FpsMovement` and `PointerControls`:
```
export class SparkControls {
  fpsMovement: FpsMovement;
  pointerControls: PointerControls;
  ...
}
```
So in your case you should just do `pointerControls.pointerRollScale = 0`. Or even easier, just pass add `pointerRollScale: 0` to your `new PointerControls({ canvas, ....etc, pointerRollScale: 0 })`.

**Comment by dmarcos** [comment]
Fixed by https://github.com/sparkjsdev/spark/issues/46

**Comment by akutterxressential** [comment]
> [@akutterxressential](https://github.com/akutterxressential) very easy fix - just a typo :). In my example I set `sparkControls.pointerControls.pointerRollScale = 0`. SparkControls is really just a wrapper that contains a `FpsMovement` and `PointerControls`:
> 
> ```
> export class SparkControls {
>   fpsMovement: FpsMovement;
>   pointerControls: PointerControls;
>   ...
> }
> ```
> 
> So in your case you should just do `pointerControls.pointerRollScale = 0`. Or even easier, just pass add `pointerRollScale: 0` to your `new PointerControls({ canvas, ....etc, pointerRollScale: 0 })`.

Thanks for the explanation. Do I need to build the changeset or can I use the dist folder content? That is what I did, upload the dist folder to my server and reference this version of spark.module.js. But it`s still not working, I can still rotate.

If I need to build first than I need to dig into this, because I haven`t setup the build environment

**Comment by dmarcos** [comment]
@akutterxressential you can now use spark 0.1.4 that we released a few hours ago!

**Comment by fragstreetboy** [comment]
> [@akutterxressential](https://github.com/akutterxressential) you can now use spark 0.1.4 that we released a few hours ago!

Wooohooo, it works like a charm! Thanks guys
